//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Specter.LINGUA {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pt_BR() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Specter.LINGUA.pt-BR", typeof(pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Voltando para a sua localização original:.
        /// </summary>
        public static string capturador_backingOriginalLoc {
            get {
                return ResourceManager.GetString("capturador_backingOriginalLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não conseguimos iniciar o processo de captura.
        /// </summary>
        public static string capturador_cannot_ProcessCaptura {
            get {
                return ResourceManager.GetString("capturador_cannot_ProcessCaptura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a fugiu! ):.
        /// </summary>
        public static string capturador_catchfle_pt2 {
            get {
                return ResourceManager.GetString("capturador_catchfle_pt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ohhh não! O Pokémon.
        /// </summary>
        public static string capturador_catchflee_pt1 {
            get {
                return ResourceManager.GetString("capturador_catchflee_pt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a foi capturado com sucesso!.
        /// </summary>
        public static string capturador_catchSucess {
            get {
                return ResourceManager.GetString("capturador_catchSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NÃO POSSÍVEL CONECTAR COM A DATABASE DO POKEMON RARO. FINALIZANDO APLICAÇÃO.
        /// </summary>
        public static string capturador_conectarPokemonRaro {
            get {
                return ResourceManager.GetString("capturador_conectarPokemonRaro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro: Erro desconhecido ao tentar capturar o Pokémon..
        /// </summary>
        public static string capturador_erroDEsconhecido {
            get {
                return ResourceManager.GetString("capturador_erroDEsconhecido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Encontramos o Pokémon.
        /// </summary>
        public static string capturador_foundPokemon {
            get {
                return ResourceManager.GetString("capturador_foundPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IV(Genética):.
        /// </summary>
        public static string capturador_genetica {
            get {
                return ResourceManager.GetString("capturador_genetica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Habilidades:.
        /// </summary>
        public static string capturador_habilidades {
            get {
                return ResourceManager.GetString("capturador_habilidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jogando.
        /// </summary>
        public static string capturador_lancandoBall {
            get {
                return ResourceManager.GetString("capturador_lancandoBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Perdemos o Pokémon!):.
        /// </summary>
        public static string capturador_lostPokemon {
            get {
                return ResourceManager.GetString("capturador_lostPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Objetos do mapa: .
        /// </summary>
        public static string capturador_mapObjects {
            get {
                return ResourceManager.GetString("capturador_mapObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a escapou de nossa.
        /// </summary>
        public static string capturador_missed {
            get {
                return ResourceManager.GetString("capturador_missed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não encontramos o Pokémon.
        /// </summary>
        public static string capturador_not_found_here_pt1 {
            get {
                return ResourceManager.GetString("capturador_not_found_here_pt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  aqui. Talvez ele já tenha sido capturado, ou ele sumiu..
        /// </summary>
        public static string capturador_not_found_here_pt2 {
            get {
                return ResourceManager.GetString("capturador_not_found_here_pt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não encontramos nada, as coordenadas estão corretas?.
        /// </summary>
        public static string capturador_NotFoundCorrectCoords {
            get {
                return ResourceManager.GetString("capturador_NotFoundCorrectCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pokémons diposniveis nesta regiao:.
        /// </summary>
        public static string capturador_pokemonRegiao {
            get {
                return ResourceManager.GetString("capturador_pokemonRegiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Procurando Pokémon... tentativa.
        /// </summary>
        public static string capturador_procurandoPokemonTentativa {
            get {
                return ResourceManager.GetString("capturador_procurandoPokemonTentativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a iniciando processo de captura do:.
        /// </summary>
        public static string capturador_startingCatching {
            get {
                return ResourceManager.GetString("capturador_startingCatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tentativa.
        /// </summary>
        public static string capturador_tentivaThrow {
            get {
                return ResourceManager.GetString("capturador_tentivaThrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não encontramos nada, desculpe. Tente outro Pokémon!.
        /// </summary>
        public static string capturador_weFoundNothing {
            get {
                return ResourceManager.GetString("capturador_weFoundNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pokémon não foi encontrado aos redores, tente procurar outro Pokemon..
        /// </summary>
        public static string capturador_weNotfound_Pokemon {
            get {
                return ResourceManager.GetString("capturador_weNotfound_Pokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar coletar os dados de sua mochila.
        /// </summary>
        public static string configuracoes_erroLoadMochila {
            get {
                return ResourceManager.GetString("configuracoes_erroLoadMochila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua mochila de Pokémons esta CHEIA..
        /// </summary>
        public static string configuracoes_FullBag {
            get {
                return ResourceManager.GetString("configuracoes_FullBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não tem pokebolas o suficiente..
        /// </summary>
        public static string configuracoes_noBall {
            get {
                return ResourceManager.GetString("configuracoes_noBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não tem POKEBOLAS e sua mochila de Pokémons esta CHEIA..
        /// </summary>
        public static string configuracoes_NoBall_Fullbag {
            get {
                return ResourceManager.GetString("configuracoes_NoBall_Fullbag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seu código foi desativado pelo Pokémon Raro.!\nCaso você acha que isso tenha sido um erro entre em contato..
        /// </summary>
        public static string frmlogin_chave_disabled_pt1 {
            get {
                return ResourceManager.GetString("frmlogin_chave_disabled_pt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CODIGO DESATIVADO.
        /// </summary>
        public static string frmlogin_chave_disabled_pt2 {
            get {
                return ResourceManager.GetString("frmlogin_chave_disabled_pt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua chave expirou!\nCompre uma nova chave para continuar utilizando..
        /// </summary>
        public static string frmlogin_chave_expirada_pt1 {
            get {
                return ResourceManager.GetString("frmlogin_chave_expirada_pt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CHAVE EXPIRADA.
        /// </summary>
        public static string frmlogin_chave_expirada_pt2 {
            get {
                return ResourceManager.GetString("frmlogin_chave_expirada_pt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A chave que você informou parece estar incorreta.\nVerifique e tente novamente..
        /// </summary>
        public static string frmlogin_chave_wrong_pt1 {
            get {
                return ResourceManager.GetString("frmlogin_chave_wrong_pt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CHAVE DE ACESSO INCORRETA.
        /// </summary>
        public static string frmlogin_chave_wrong_pt2 {
            get {
                return ResourceManager.GetString("frmlogin_chave_wrong_pt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua chave expirou [Total:.
        /// </summary>
        public static string frmlogin_chaveExpirada {
            get {
                return ResourceManager.GetString("frmlogin_chaveExpirada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conectado..
        /// </summary>
        public static string frmlogin_Conectado {
            get {
                return ResourceManager.GetString("frmlogin_Conectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estado Servidor:.
        /// </summary>
        public static string frmlogin_estadoServidor {
            get {
                return ResourceManager.GetString("frmlogin_estadoServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LINGUA:.
        /// </summary>
        public static string frmlogin_Lingua {
            get {
                return ResourceManager.GetString("frmlogin_Lingua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SAIR.
        /// </summary>
        public static string frmlogin_Sair {
            get {
                return ResourceManager.GetString("frmlogin_Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Versão:.
        /// </summary>
        public static string frmlogin_Versao {
            get {
                return ResourceManager.GetString("frmlogin_Versao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esta versão do Specter se encontra desatualizada.\nFaça download da nova versão para continuar utilizando..
        /// </summary>
        public static string frmlogin_versao_Desatualizada_pt1 {
            get {
                return ResourceManager.GetString("frmlogin_versao_Desatualizada_pt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VERSÃO DESATUALIZADA.
        /// </summary>
        public static string frmlogin_versao_Desatualizada_pt2 {
            get {
                return ResourceManager.GetString("frmlogin_versao_Desatualizada_pt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desatualzada..
        /// </summary>
        public static string frmlogin_Versao_dezatualizada {
            get {
                return ResourceManager.GetString("frmlogin_Versao_dezatualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [ERRO]:.
        /// </summary>
        public static string loggin_error {
            get {
                return ResourceManager.GetString("loggin_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [INFO]:.
        /// </summary>
        public static string loggin_info {
            get {
                return ResourceManager.GetString("loggin_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [POKÉMON-RARO]:.
        /// </summary>
        public static string loggin_pokeraro {
            get {
                return ResourceManager.GetString("loggin_pokeraro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [SUCESSO]:.
        /// </summary>
        public static string loggin_sucess {
            get {
                return ResourceManager.GetString("loggin_sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [AVISO]:.
        /// </summary>
        public static string loggin_warning {
            get {
                return ResourceManager.GetString("loggin_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você deixou um outro campo em branco..
        /// </summary>
        public static string manual_campoBranco_pt1 {
            get {
                return ResourceManager.GetString("manual_campoBranco_pt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ERRO.
        /// </summary>
        public static string manual_campoBranco_pt2 {
            get {
                return ResourceManager.GetString("manual_campoBranco_pt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CAPTURA.
        /// </summary>
        public static string manual_catch {
            get {
                return ResourceManager.GetString("manual_catch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CAPTURAR.
        /// </summary>
        public static string manual_catcher {
            get {
                return ResourceManager.GetString("manual_catcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CAPTURA MANUAL.
        /// </summary>
        public static string manual_catchManual {
            get {
                return ResourceManager.GetString("manual_catchManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FECHAR.
        /// </summary>
        public static string manual_close {
            get {
                return ResourceManager.GetString("manual_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Existe algum erro no formato do texto da captura. .
        /// </summary>
        public static string manual_errorFomatoString {
            get {
                return ResourceManager.GetString("manual_errorFomatoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exemplo: Dragonite,34.43434,-66.343443.
        /// </summary>
        public static string manual_example {
            get {
                return ResourceManager.GetString("manual_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formato: NomeDoPokemon, Latitude, Longitude.
        /// </summary>
        public static string manual_format {
            get {
                return ResourceManager.GetString("manual_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Encontramos 0 Pokémons..
        /// </summary>
        public static string pesquisa_Poke_0PokemonEncontrado {
            get {
                return ResourceManager.GetString("pesquisa_Poke_0PokemonEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não encontramos coordenada deste Pokémon no momento. Tente mais tarde..
        /// </summary>
        public static string pesquisa_Poke_naoEncontrado {
            get {
                return ResourceManager.GetString("pesquisa_Poke_naoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível obter as coordenadas dos Pokémons..
        /// </summary>
        public static string pesquisa_Poke_naoPossivelEncontrar {
            get {
                return ResourceManager.GetString("pesquisa_Poke_naoPossivelEncontrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você digitou o nome do Pokémon incorretamente!.
        /// </summary>
        public static string pesquisa_Poke_nomeIncorreto {
            get {
                return ResourceManager.GetString("pesquisa_Poke_nomeIncorreto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Servidor não retornou nenhum dado de Pokémon. Tente novamente..
        /// </summary>
        public static string pesquisa_Server_semData {
            get {
                return ResourceManager.GetString("pesquisa_Server_semData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entre no site e descubra as coordenadas de onde você vive..
        /// </summary>
        public static string price_siteFindLocation {
            get {
                return ResourceManager.GetString("price_siteFindLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a COMO GERAR SENHA DE APP.
        /// </summary>
        public static string princ_appPass {
            get {
                return ResourceManager.GetString("princ_appPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ORDEM POKEBOLA.
        /// </summary>
        public static string princ_ballOrder {
            get {
                return ResourceManager.GetString("princ_ballOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a POKEBOLAS:.
        /// </summary>
        public static string princ_balls {
            get {
                return ResourceManager.GetString("princ_balls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CAPTURA MANUAL.
        /// </summary>
        public static string princ_CatchManual {
            get {
                return ResourceManager.GetString("princ_CatchManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CAPTURAR [Razzberry].
        /// </summary>
        public static string princ_catchRazz {
            get {
                return ResourceManager.GetString("princ_catchRazz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CAPTURAR [RazzBerry+PinapBerry].
        /// </summary>
        public static string princ_catchRazzPinap {
            get {
                return ResourceManager.GetString("princ_catchRazzPinap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PERSONAGEM.
        /// </summary>
        public static string princ_character {
            get {
                return ResourceManager.GetString("princ_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a COMPRAR CHAVE.
        /// </summary>
        public static string princ_chave {
            get {
                return ResourceManager.GetString("princ_chave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Completar Pokedex.
        /// </summary>
        public static string princ_complete {
            get {
                return ResourceManager.GetString("princ_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe as coordenadas do Pokemon.
        /// </summary>
        public static string princ_Coords {
            get {
                return ResourceManager.GetString("princ_Coords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a COPIAR COORDENADAS.
        /// </summary>
        public static string princ_CopyCoords {
            get {
                return ResourceManager.GetString("princ_CopyCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados de login.
        /// </summary>
        public static string princ_dadosLogin {
            get {
                return ResourceManager.GetString("princ_dadosLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desativado no momento. Em desenvolvimento..
        /// </summary>
        public static string princ_disabledNow {
            get {
                return ResourceManager.GetString("princ_disabledNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desativado no momento. Em desenvolvimento..
        /// </summary>
        public static string princ_disabledNow2 {
            get {
                return ResourceManager.GetString("princ_disabledNow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ERROS, BUGS, SOLUÇÕES.
        /// </summary>
        public static string princ_ErrorBug {
            get {
                return ResourceManager.GetString("princ_ErrorBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IV (Genética).
        /// </summary>
        public static string princ_genetica {
            get {
                return ResourceManager.GetString("princ_genetica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Como a lista dos Pokémons será mostrada..
        /// </summary>
        public static string princ_listTip {
            get {
                return ResourceManager.GetString("princ_listTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua localização.
        /// </summary>
        public static string princ_location {
            get {
                return ResourceManager.GetString("princ_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NOME.
        /// </summary>
        public static string princ_name {
            get {
                return ResourceManager.GetString("princ_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NOME DOS POKÉMONS DISPONÍVEIS.
        /// </summary>
        public static string princ_NamePoke {
            get {
                return ResourceManager.GetString("princ_NamePoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Numero Pokedex.
        /// </summary>
        public static string princ_numeroPokedex {
            get {
                return ResourceManager.GetString("princ_numeroPokedex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PAGINA OFICIAL.
        /// </summary>
        public static string princ_oficialpage {
            get {
                return ResourceManager.GetString("princ_oficialpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atualmente em desenvolvimento..
        /// </summary>
        public static string princ_onDev {
            get {
                return ResourceManager.GetString("princ_onDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ORDEM LISTA:.
        /// </summary>
        public static string princ_ordemList {
            get {
                return ResourceManager.GetString("princ_ordemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Digite o nome sem espaços, virulas ou acentos..
        /// </summary>
        public static string princ_PokemonName {
            get {
                return ResourceManager.GetString("princ_PokemonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PROCURAR.
        /// </summary>
        public static string princ_Procurar {
            get {
                return ResourceManager.GetString("princ_Procurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recarregar Pokemons.
        /// </summary>
        public static string princ_reload {
            get {
                return ResourceManager.GetString("princ_reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a REMOVEDOR SOFTBAN.
        /// </summary>
        public static string princ_RemovedorSoft {
            get {
                return ResourceManager.GetString("princ_RemovedorSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SENHA/S. APP.
        /// </summary>
        public static string princ_senhaApp {
            get {
                return ResourceManager.GetString("princ_senhaApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Iniciar captura.
        /// </summary>
        public static string princ_start {
            get {
                return ResourceManager.GetString("princ_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TIME.
        /// </summary>
        public static string princ_team {
            get {
                return ResourceManager.GetString("princ_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tempo Restante.
        /// </summary>
        public static string princ_timeLeft {
            get {
                return ResourceManager.GetString("princ_timeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OPÇÃO PAGA..
        /// </summary>
        public static string princ_tipIV {
            get {
                return ResourceManager.GetString("princ_tipIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Digite o nome sem espaços, virulas ou acentos..
        /// </summary>
        public static string princ_TipName {
            get {
                return ResourceManager.GetString("princ_TipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha para Pokémon Trainer Clube &amp; Senha de APP para contas Google..
        /// </summary>
        public static string princ_TipSenha {
            get {
                return ResourceManager.GetString("princ_TipSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome de Usuario para contas PTC &amp; E-mail para contas Google..
        /// </summary>
        public static string princ_TipUserEmail {
            get {
                return ResourceManager.GetString("princ_TipUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a T.CAPTURADO:.
        /// </summary>
        public static string princ_totalCatch {
            get {
                return ResourceManager.GetString("princ_totalCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a T.ESCAPADO:.
        /// </summary>
        public static string princ_totalEscaped {
            get {
                return ResourceManager.GetString("princ_totalEscaped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de Conta.
        /// </summary>
        public static string princ_typeConta {
            get {
                return ResourceManager.GetString("princ_typeConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a USUARIO/E-MAIL.
        /// </summary>
        public static string princ_userEmail {
            get {
                return ResourceManager.GetString("princ_userEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DESLOGAR.
        /// </summary>
        public static string prince_Deslogar {
            get {
                return ResourceManager.GetString("prince_Deslogar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DESCUBRA SUA LOCALIZAÇÃO.
        /// </summary>
        public static string prince_findLocation {
            get {
                return ResourceManager.GetString("prince_findLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contas que utilizam o Google para realizar o login..
        /// </summary>
        public static string prince_GoogleTrainer {
            get {
                return ResourceManager.GetString("prince_GoogleTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atualmente em desenvolvimento..
        /// </summary>
        public static string prince_inDev {
            get {
                return ResourceManager.GetString("prince_inDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LOGAR.
        /// </summary>
        public static string prince_Login {
            get {
                return ResourceManager.GetString("prince_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ATIVIDADES.
        /// </summary>
        public static string prince_logs {
            get {
                return ResourceManager.GetString("prince_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do Pokemon.
        /// </summary>
        public static string prince_nomePoke {
            get {
                return ResourceManager.GetString("prince_nomePoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome de Usuario para contas PTC &amp; E-mail para contas Google..
        /// </summary>
        public static string prince_nomeUser {
            get {
                return ResourceManager.GetString("prince_nomeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contas que utilizam o Pokémon Trainer Clube para realizar o login..
        /// </summary>
        public static string prince_Poketrainer {
            get {
                return ResourceManager.GetString("prince_Poketrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha para Pokémon Trainer Clube &amp; Senha de APP para contas Google..
        /// </summary>
        public static string prince_senhaApp {
            get {
                return ResourceManager.GetString("prince_senhaApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VERSÃO:.
        /// </summary>
        public static string prince_versao {
            get {
                return ResourceManager.GetString("prince_versao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Capturando o.
        /// </summary>
        public static string principal_catching {
            get {
                return ResourceManager.GetString("principal_catching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Capturando Pokémon, aguarde..
        /// </summary>
        public static string principal_catchingPokemonWait {
            get {
                return ResourceManager.GetString("principal_catchingPokemonWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CAPTURAR.
        /// </summary>
        public static string principal_catchToolStrp_Enabled {
            get {
                return ResourceManager.GetString("principal_catchToolStrp_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CAPTURAR MANUAL.
        /// </summary>
        public static string principal_catchToolStrp_Manual_Enabled {
            get {
                return ResourceManager.GetString("principal_catchToolStrp_Manual_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados do personagem carregados com sucesso!.
        /// </summary>
        public static string principal_dadosCharSucess {
            get {
                return ResourceManager.GetString("principal_dadosCharSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Realize o login antes de iniciar a captura..
        /// </summary>
        public static string principal_doLogin_Before_Catch {
            get {
                return ResourceManager.GetString("principal_doLogin_Before_Catch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LOGIN: você deixou algum campo na area de login em branco..
        /// </summary>
        public static string principal_esqueceu_campo_brancoLogin {
            get {
                return ResourceManager.GetString("principal_esqueceu_campo_brancoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LOGIN: Você esqueceu de selecionar o tipo de sua conta. PTC ou Google?.
        /// </summary>
        public static string principal_esqueceu_tipoConta_Login {
            get {
                return ResourceManager.GetString("principal_esqueceu_tipoConta_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logado com sucesso!.
        /// </summary>
        public static string principal_LogadoSucesso {
            get {
                return ResourceManager.GetString("principal_LogadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deslogando....
        /// </summary>
        public static string principal_logOff {
            get {
                return ResourceManager.GetString("principal_logOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deslogado com sucesso!.
        /// </summary>
        public static string principal_logOffSucess {
            get {
                return ResourceManager.GetString("principal_logOffSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a nas coordenadas.
        /// </summary>
        public static string principal_onCoordinates {
            get {
                return ResourceManager.GetString("principal_onCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PROCURANDO....
        /// </summary>
        public static string principal_procurando {
            get {
                return ResourceManager.GetString("principal_procurando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PROCURAR.
        /// </summary>
        public static string principal_procurar {
            get {
                return ResourceManager.GetString("principal_procurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A versão minima do jogo se atualizou para.
        /// </summary>
        public static string principal_versaoMinima_pt1 {
            get {
                return ResourceManager.GetString("principal_versaoMinima_pt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Isso significa que no momento não é seguro utilizar o Specter. Aguarde a equipe do PokémonRaro atualizar para a nova versão..
        /// </summary>
        public static string principal_versaoMinima_pt2 {
            get {
                return ResourceManager.GetString("principal_versaoMinima_pt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Versão minima insuficiente.
        /// </summary>
        public static string principal_versaoMinima_pt3 {
            get {
                return ResourceManager.GetString("principal_versaoMinima_pt3", resourceCulture);
            }
        }
    }
}
